env:
  es2021: true
  node: true
  jest: true
extends: airbnb-base
overrides: [
  {
    files: './bin/**/*.js',
    rules: {
      no-console: off
    }
  }
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: ['error', 'ignorePackages']
  no-underscore-dangle: ['error', {
    allow: ['__filename', '__dirname']
  }]
