name: node CI
on: push
jobs:
  code-check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checking out
        uses: actions/checkout@v3
      - name: dependencies installation
        run: npm ci
      - name: linting & testing
        run: |
          make lint
          make test
      - name: coverage upload
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make coverage
